exec python -m src.train \
  --data_dir preprocessed_file \
  --save_path checkpoints/textcnn_glove.pt \
  --glove_path embeddings/glove.6B.100d.txt \
  --max_len 48 \
  --embed_dim 100 \
  --num_filters 100 \
  --kernel_sizes 3 4 5 \
  --dropout 0.5 \
  --batch_size 64 \
  --epochs 15 \
  --lr 8e-4 \
  --weight_decay 1e-4